version: '3.0'

services:
  app:
    image: app
    build: ./test
    ports:
      - 8000:8000

  prometheus:
    image: quay.io/prometheus/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command: "--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090

  grafana:
    container_name: 'grafana'
    image: grafana/grafana
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./dist:/var/lib/grafana/plugins/basic-panel
      - ./grafana/provisioning:/etc/grafana/provisioning

